<?php

namespace Proxies\__CG__\Optimus\OptimusBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BuildingPartitioning extends \Optimus\OptimusBundle\Entity\BuildingPartitioning implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\BuildingPartitioning' . "\0" . 'id', 'fk_Building', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\BuildingPartitioning' . "\0" . 'partitionName', 'children', 'fk_BuildingPartitioning', 'energy_consumption', 'max_capacity');
        }

        return array('__isInitialized__', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\BuildingPartitioning' . "\0" . 'id', 'fk_Building', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\BuildingPartitioning' . "\0" . 'partitionName', 'children', 'fk_BuildingPartitioning', 'energy_consumption', 'max_capacity');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BuildingPartitioning $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkBuilding(\Optimus\OptimusBundle\Entity\Building $fkBuilding = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkBuilding', array($fkBuilding));

        return parent::setFkBuilding($fkBuilding);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkBuilding()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkBuilding', array());

        return parent::getFkBuilding();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartitionName($partitionName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartitionName', array($partitionName));

        return parent::setPartitionName($partitionName);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartitionName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartitionName', array());

        return parent::getPartitionName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkBuildingPartitioning(\Optimus\OptimusBundle\Entity\BuildingPartitioning $fkBuildingPartitioning)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkBuildingPartitioning', array($fkBuildingPartitioning));

        return parent::setFkBuildingPartitioning($fkBuildingPartitioning);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkBuildingPartitioning()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkBuildingPartitioning', array());

        return parent::getFkBuildingPartitioning();
    }

    /**
     * {@inheritDoc}
     */
    public function addChild(\Optimus\OptimusBundle\Entity\BuildingPartitioning $children)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChild', array($children));

        return parent::addChild($children);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChild(\Optimus\OptimusBundle\Entity\BuildingPartitioning $children)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChild', array($children));

        return parent::removeChild($children);
    }

    /**
     * {@inheritDoc}
     */
    public function getChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildren', array());

        return parent::getChildren();
    }

    /**
     * {@inheritDoc}
     */
    public function getEnergyConsumption()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnergyConsumption', array());

        return parent::getEnergyConsumption();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnergyConsumption($energy_consumption)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnergyConsumption', array($energy_consumption));

        return parent::setEnergyConsumption($energy_consumption);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxCapacity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxCapacity', array());

        return parent::getMaxCapacity();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxCapacity($max_capacity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxCapacity', array($max_capacity));

        return parent::setMaxCapacity($max_capacity);
    }

}
