<?php

namespace Proxies\__CG__\Optimus\OptimusBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Building extends \Optimus\OptimusBundle\Entity\Building implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\Building' . "\0" . 'id', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\Building' . "\0" . 'name', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\Building' . "\0" . 'city', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\Building' . "\0" . 'street', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\Building' . "\0" . 'use_building', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\Building' . "\0" . 'year_of_construction', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\Building' . "\0" . 'surface', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\Building' . "\0" . 'occupation');
        }

        return array('__isInitialized__', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\Building' . "\0" . 'id', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\Building' . "\0" . 'name', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\Building' . "\0" . 'city', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\Building' . "\0" . 'street', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\Building' . "\0" . 'use_building', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\Building' . "\0" . 'year_of_construction', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\Building' . "\0" . 'surface', '' . "\0" . 'Optimus\\OptimusBundle\\Entity\\Building' . "\0" . 'occupation');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Building $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreet($street)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreet', array($street));

        return parent::setStreet($street);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet', array());

        return parent::getStreet();
    }

    /**
     * {@inheritDoc}
     */
    public function setUse($use)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUse', array($use));

        return parent::setUse($use);
    }

    /**
     * {@inheritDoc}
     */
    public function getUse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUse', array());

        return parent::getUse();
    }

    /**
     * {@inheritDoc}
     */
    public function setYearOfConstruction($yearOfConstruction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYearOfConstruction', array($yearOfConstruction));

        return parent::setYearOfConstruction($yearOfConstruction);
    }

    /**
     * {@inheritDoc}
     */
    public function getYearOfConstruction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYearOfConstruction', array());

        return parent::getYearOfConstruction();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurface($surface)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurface', array($surface));

        return parent::setSurface($surface);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurface()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurface', array());

        return parent::getSurface();
    }

    /**
     * {@inheritDoc}
     */
    public function setOccupation($occupation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOccupation', array($occupation));

        return parent::setOccupation($occupation);
    }

    /**
     * {@inheritDoc}
     */
    public function getOccupation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOccupation', array());

        return parent::getOccupation();
    }

    /**
     * {@inheritDoc}
     */
    public function setUseBuilding($useBuilding)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUseBuilding', array($useBuilding));

        return parent::setUseBuilding($useBuilding);
    }

    /**
     * {@inheritDoc}
     */
    public function getUseBuilding()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUseBuilding', array());

        return parent::getUseBuilding();
    }

}
