<?php

namespace Optimus\OptimusBundle\Servicios;

use Symfony\Component\Config\FileLocator;
use Doctrine\ORM\EntityManager;



class ServiceAPEnergySource {

    protected $em;
    
	// Sensors
	//protected $ontologia;
	//protected $invokePredictData; 
	protected $events;
	
	private static $sensor_1_airtemperature_name = "Air temperature (forecast) (C)";	
	private static $sensor_2_relativehumidity_name = "Relative humidity (forecast) (%)";	
	private static $sensor_3_airpressure_name = "Air pressure (forecast) (mbar)";	
    private static $sensor_4_solarradiation_name = "Solar radiation (forecast) (W/m2)";	
    private static $sensor_5_energyproduction_name = "Energy production (Kwh)";	
	private static $sensor_6_powerexchangednetwork_name = "Electrical power exchanged with the external network (Kwh)";	
	private static $sensor_7_powerexchangedfiamm_name = "Electrical power exchanged by the FIAMM SoNick storage system (Kwh)";	
    private static $sensor_8_electricaldualmodemicroturbine_name = "Electrical power generated by the dual mode Capstone microturbine (Kwh)";	
    private static $sensor_9_electricalgridmicroturbine_name = "Electrical power generated by the grid connected Capstone microturbine (Kwh)";	
    private static $sensor_10_thermaldualmodemicroturbine_name = "Thermal power delivered by the dual mode Capstone microturbine (Kwh)";	
    private static $sensor_11_thermalgridmicroturbine_name = "Thermal power delivered by the the grid connected Capstone microturbine (Kwh)";	
    private static $sensor_12_thermalboilers_name = "Thermal power delivered by the boilers (Kwh)";
	
	//private static $sensor_PV_rad = "PV_rad";	
	//private static $sensor_PV_Pel = "PV_Pel"; 
	//private static $sensor_CHP_C65B_Pel = "CHP_C65B_Pel"; 
	//private static $sensor_CHP_C65_Pel = "CHP_C65_Pel";
	//private static $sensor_STO_Pel = "STO_Pe";
	//private static $sensor_NET_Pel = "NET_Pel";		
	//private static $sensor_BO_Pth = "BO_Pth";	
	
	public function getAirtemperatureName(){return self::$sensor_1_airtemperature_name;}
	public function getRelativehumidityName(){return self::$sensor_2_relativehumidity_name;}
	public function getAirpressureName(){return self::$sensor_3_airpressure_name;}
	public function getSolarradiationName(){return self::$sensor_4_solarradiation_name;}
	public function getEnergyproductionName(){return self::$sensor_5_energyproduction_name;}
	public function getPowerexchangednetworkName(){return self::$sensor_6_powerexchangednetwork_name;}
	public function getPowerexchangedfiammName(){return self::$sensor_7_powerexchangedfiamm_name;}
	public function getElectricaldualmodemicroturbineName(){return self::$sensor_8_electricaldualmodemicroturbine_name;}
	public function getElectricalgridmicroturbineName(){return self::$sensor_9_electricalgridmicroturbine_name;}
	public function getThermaldualmodemicroturbineName(){return self::$sensor_10_thermaldualmodemicroturbine_name;}
	public function getThermalgridmicroturbineName(){return self::$sensor_11_thermalgridmicroturbine_name;}
	public function getThermalboilersName(){return self::$sensor_12_thermalboilers_name;}
	
	//public function getPV_radName(){return self::$sensor_PV_rad;}
	//public function getPV_PelName(){return self::$sensor_PV_Pel;}
	//public function getCHP_C65B_PelName(){return self::$sensor_CHP_C65B_Pel;}
	//public function getCHP_C65_PelName(){return self::$sensor_CHP_C65_Pel;}
	//public function getCHP_STO_PelName(){return self::$sensor_STO_Pel;}
	//public function getNET_PelName(){return self::$sensor_NET_Pel;}
	//public function getCHP_BO_PthName(){return self::$sensor_BO_Pth;}
	
	public function getDataVariablesInput()
	{
		$aVariablesInput=array();
		
		$aVariablesInput[].=self::$sensor_1_airtemperature_name;
		$aVariablesInput[].=self::$sensor_2_relativehumidity_name;
		$aVariablesInput[].=self::$sensor_3_airpressure_name;
		$aVariablesInput[].=self::$sensor_4_solarradiation_name;
		$aVariablesInput[].=self::$sensor_5_energyproduction_name;
		$aVariablesInput[].=self::$sensor_6_powerexchangednetwork_name;
		$aVariablesInput[].=self::$sensor_7_powerexchangedfiamm_name;
		$aVariablesInput[].=self::$sensor_8_electricaldualmodemicroturbine_name;
		$aVariablesInput[].=self::$sensor_9_electricalgridmicroturbine_name;
		$aVariablesInput[].=self::$sensor_10_thermaldualmodemicroturbine_name;
		$aVariablesInput[].=self::$sensor_11_thermalgridmicroturbine_name;
		$aVariablesInput[].=self::$sensor_12_thermalboilers_name;
		
		//$aVariablesInput[].=self::$sensor_PV_rad;
		//$aVariablesInput[].=self::$sensor_PV_Pel;
		//$aVariablesInput[].=self::$sensor_CHP_C65B_Pel;
		//$aVariablesInput[].=self::$sensor_CHP_C65_Pel;
		//$aVariablesInput[].=self::$sensor_STO_Pel;
		//$aVariablesInput[].=self::$sensor_NET_Pel;
		//$aVariablesInput[].=self::$sensor_BO_Pth;
		
		return $aVariablesInput;
	}
	
	//Sensors\
	
	
    public function __construct(EntityManager $em)
    {
        $this->em=$em;
    }
	
    /*
     * Run the service
     * The result is an array containing
     *   - Input from sensors (e.g 'actual_humidity', 'air_temperature')
     *   - Feedback from TCV ('feedback')
     *   - The proposed temperature ('proposed_temperature')
     */
    public function invoke_service($building_id) {
        $result = array();
        /* Get initial data about the building */
        $building = $this->em->getRepository('OptimusOptimusBundle:Building')->find($building_id);
        $result['building'] = $building;
		
        $week = array();
        $dataDaily = array();
		
		/* Open the input file: 'Real.csv', now 'LoadShift.csv' */
        $configDirectories = array(__DIR__.'\Util\EnergySource');
        $locator = new FileLocator($configDirectories);
        $path = $locator->locate('LoadShift_combined.csv', null, false)[0];
		
		$file_shaving = fopen($path,"r");
		
        fgetcsv($file_shaving);
		$dataHourly = array();
		$batteryUse = array();
        if(! feof($file_shaving)){
			$row = fgetcsv($file_shaving);
			$date = substr($row['1'], 0, 10);
			$hour = substr($row['1'], 11, 2);
			for($i=0; $i<$hour; $i++){
				array_push($dataHourly, array("consumption"=> 'undefined', "production"=> 'undefined', "grid"=> 'undefined', "finalSuggestion"=> 'undefined', "consumptionShifted"=> 'undefined', "gridShifted"=> 'undefined', "load"=>'undefined', "gridOriginal"=> 'undefined', "batteryUse"=>'undefined'));
				array_push($batteryUse, 'undefined');
			}
			array_push($dataHourly, array("consumption"=> $row['0'], "production"=> $row['4'], "grid"=> $row['0'], "finalSuggestion"=> $row['3'], "consumptionShifted"=> $row['2'] + $row['3'], "gridShifted"=> $row['0'] + $row['3'], "load"=> $row['2'], "gridOriginal"=> $row['6'], "batteryUse"=> $row['7']));
			array_push($batteryUse, $row['7']);
		}
		$start_hour = $hour;
		for($i=0; $i<(24*7 - $start_hour); $i++){
			if(! feof($file_shaving)){
				$row = fgetcsv($file_shaving);
				$date = substr($row['1'], 0, 10);
				$hour = substr($row['1'], 11, 2);
				array_push($dataHourly, array("consumption"=> $row['0'], "production"=> $row['4'], "grid"=> $row['0'], "finalSuggestion"=> $row['3'], "consumptionShifted"=> $row['2'] + $row['3'], "gridShifted"=> $row['0'] + $row['3'],"load"=> $row['2'], "gridOriginal"=> $row['6'], "batteryUse"=> $row['7']));
				array_push($batteryUse, $row['7']);
			}
			else{
				array_push($dataHourly, array("consumption"=> 'undefined', "production"=> 'undefined', "grid"=> 'undefined', "finalSuggestion"=> 'undefined', "consumptionShifted"=> 'undefined', "gridShifted"=> 'undefined', "load"=> 'undefined', "gridOriginal"=> 'undefined', "batteryUse"=>'undefined'));
				array_push($batteryUse, 'undefined');
			}
		}
		
		fclose($file_shaving);
		
      
		
		
		
		//for($i=0; $i<24*7; $i++){
			//array_push($batteryUse, $row['7']);
			//array_push($batteryUse, "no data");
		//}
		
		
		for($j=0; $j<7; $j++){
			$dayData = array("consumption"=> 0, "production"=> 0, "grid"=> 0, "load"=> 0);
			for($i=0; $i<24; $i++){
				if($dataHourly[$j*24+$i]["consumption"] != "undefined"){
					$dayData["consumption"] += $dataHourly[$j*24+$i]["consumption"];
					$dayData["production"] += $dataHourly[$j*24+$i]["production"];
					$dayData["grid"] += $dataHourly[$j*24+$i]["grid"];
					$dayData["load"] += $dataHourly[$j*24+$i]["load"];
				}
			}
			array_push($dataDaily, $dayData);
		}
		
        //array_splice($dataHourly, count($dataHourly)-1, 1);
        
		$result['week'] = $week;
		$result['dataDaily'] = $dataDaily;
		$result['dataHourly'] = $dataHourly;
		$result['batteryUse'] = $batteryUse;
		
		
		
        return $result;
    }
}
?>
